### ISSUE TITLE
Left click on menubar icon should always bring Webbuddy forward

### ISSUE THREAD

**Issue by frykauf** [bigbearlabs/webbuddy-support#169]
Right click for options

**Comment by sohocoke** [comment]
@frykauf in the latest version I implemented right-click to toggle browser window visibility. Enjoy!

**Comment by frykauf** [comment]
Love this, thank you so much ❤️ 

But could you please also make it so even if the window isn’t hidden, just in the background (behind other windows) it’s also brought in the foreground with single right click? (right now you have to essentially click 2x - hide and unhide it - and it can cut off music you’re playing in the background and so on by having to hide the window first).

Anyway that is a small thing. Thank you for already putting this in 👍

**Comment by sohocoke** [comment]
@frykauf  I'll add this to the next release.

**Comment by sohocoke** [comment]
@frykauf just a heads-up; this should be in the latest release.

**Comment by frykauf** [comment]
Oh yes, I forgot to close it :)
And thanks for adding it.
