### ISSUE TITLE
site: take new screenshot

### ISSUE THREAD

**Issue by sohocoke** [bigbearlabs/webbuddy-support#47]

**Comment by philippkueng** [comment]
both of us will take a couple of screenshots and then we compare which one is the best

**Comment by sohocoke** [comment]
hi philipp, any updates on the photoshopping action?

**Comment by sohocoke** [comment]
The size in the intro screen is quite ineffective.

For now we move on, but it looks like we need to budget more to get the screenshots done effectively.
