### ISSUE TITLE
site: send all credentials to philipp

### ISSUE THREAD

**Issue by sohocoke** [bigbearlabs/webbuddy-support#53]
-tumblr-
-squarespace-
-dns-
aws
google analytics

**Comment by sohocoke** [comment]
Sent access for tumblr, squarespace, domain name provider, google analytics. 

Can't figure out how to manage aws access - created user 'philippkueng' in group 'council', but I have no idea what I'm doing there.

**Comment by philippkueng** [comment]
Unfortunately i've never shared an account before. ...i'd recommend just creating a new account, dedicated to bbl and send me the credentials to that one. obviously the sharing the account over the AWS permission system would be nicer, but if it's taking us that long i'm not sure it's worth it.

**Comment by sohocoke** [comment]
Product available at http://bigbearlabs.com/downloads/WebBuddy.zip, working around the colossal task of figuring out AWS access control.

**Comment by philippkueng** [comment]
ok, but at some point you might need to do it anyway. ...i can help you next time. thanks for the link though.

**Comment by sohocoke** [comment]
Yeah, I'd like to get it moved over eventually. At least it's not a blocker for now.
