### ISSUE TITLE
site: send/share all the media files for bbl and webbuddy with philipp

### ISSUE THREAD

**Issue by philippkueng** [bigbearlabs/webbuddy-support#55]
- bbl-logo
- bbl-font
- webbuddy-logo

**Comment by sohocoke** [comment]
Uploaded the .ai files to dropbox. I don't have illustrator but hopefully we can get the font names from them too.

**Comment by philippkueng** [comment]
That would be cool. I think it's either MyriadWebPro-Bold or RussoOne
...both of them i don't currently own.

**Comment by sohocoke** [comment]
Font according to AI is RussoOne
