### ISSUE TITLE
retina icon for the menu bar.

### ISSUE THREAD

**Issue by sohocoke** [bigbearlabs/webbuddy-support#57]

**Comment by sohocoke** [comment]
@philippkueng I uploaded a new version (1.1.6) that has a retina icon. Now.. the retina version is actually a different design - I wonder whether it is suitable. Could you give it a run and see if you like it, and if it blends in in your environment? Thanks.

**Comment by philippkueng** [comment]
i'll try it after lunch today, sorry for the delay.

**Comment by sohocoke** [comment]
BW icon has been retina-fied, committed to the feature branch for 1.2.
1.1 has a visually noisy icon for retina, but since this item is tied to App Store release, we're not going for the rolls royce for this item on 1.1.
