### ISSUE TITLE
site: include s3 downloads in analytics

### ISSUE THREAD

**Issue by sohocoke** [bigbearlabs/webbuddy-support#96]
somehow.

**Comment by philippkueng** [comment]
the only way to achieve that is to enable S3 bucket logging and then parse the request logs (similar to apache logs) Amazon writes when someone accesses a file. ...not trivial but doable. though not sure if worth the effort at that point, having a redirect (let's say via bit.ly) to the file is probably easier.

**Comment by sohocoke** [comment]
So page points to bit.ly, this shows up on Google Analytics, url gets redirected to url of file on S3?

**Comment by philippkueng** [comment]
Nope, page is still on heroku. but the download link is being redirected via bitly.
